version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile-debug
      args:
        - rm=false
    links:
      - db
    restart: always
    env_file: ferda.env
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - 8081:8080
      - 40000:40000
  db:
    image: postgres:12
    restart: always
    env_file: ferda.env
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data