version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - rm=false
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/ferda
    links:
      - db
    restart: always
    env_file: ferda.env
  db:
    image: postgres:12
    restart: always
    env_file: ferda.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data